PRAGMA foreign_keys = ON;
CREATE TABLE git_observations (
 id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES projects(id), idempotency_key TEXT NOT NULL UNIQUE,
 actor_session_id TEXT NOT NULL REFERENCES agent_sessions(id), task_id TEXT NOT NULL REFERENCES tasks(id), run_id TEXT NOT NULL REFERENCES task_runs(id), trigger_kind TEXT NOT NULL CHECK(trigger_kind='scan'),
 observed_at TEXT NOT NULL CHECK(length(observed_at)=30 AND observed_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]Z'),
 revision TEXT NOT NULL CHECK(revision='git-observation/v1'), observation_hash TEXT NOT NULL CHECK(length(observation_hash)=64 AND observation_hash NOT GLOB '*[^0-9a-f]*'), repository_state TEXT NOT NULL CHECK(repository_state IN ('unknown','non_git','bare','worktree')), confidence TEXT NOT NULL CHECK(confidence IN ('observed','incomplete','unknown')), common_dir TEXT NOT NULL CHECK(length(common_dir)<=4096), top_level TEXT NOT NULL CHECK(length(top_level)<=4096), default_branch TEXT NOT NULL CHECK(length(default_branch)<=1024), sequence_no INTEGER NOT NULL CHECK(sequence_no>0), UNIQUE(project_id,sequence_no)
);
CREATE TABLE git_observation_assets (
 id TEXT PRIMARY KEY, observation_id TEXT NOT NULL REFERENCES git_observations(id), fingerprint TEXT NOT NULL CHECK(length(fingerprint)=64 AND fingerprint NOT GLOB '*[^0-9a-f]*'), asset_type TEXT NOT NULL CHECK(asset_type IN ('main_worktree','linked_worktree','local_branch','detached_head')),
 first_seen_at TEXT NOT NULL CHECK(length(first_seen_at)=30 AND first_seen_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]Z'), last_seen_at TEXT NOT NULL CHECK(length(last_seen_at)=30 AND last_seen_at GLOB '[0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]T[0-9][0-9]:[0-9][0-9]:[0-9][0-9].[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]Z' AND first_seen_at<=last_seen_at),
 facts_confidence TEXT NOT NULL CHECK(facts_confidence IN ('observed','incomplete','unknown')), worktree_path TEXT NOT NULL CHECK(length(worktree_path)<=4096), branch TEXT NOT NULL CHECK(length(branch)<=1024), detached INTEGER NOT NULL CHECK(detached IN (0,1)), branch_only INTEGER NOT NULL CHECK(branch_only IN (0,1)), default_branch INTEGER NOT NULL CHECK(default_branch IN (0,1)), worktree_prunable INTEGER NOT NULL CHECK(worktree_prunable IN (0,1)),
 status_branch TEXT NOT NULL CHECK(length(status_branch)<=1024), status_head TEXT NOT NULL CHECK(length(status_head)<=1024), status_detached INTEGER NOT NULL CHECK(status_detached IN (0,1)), status_upstream TEXT NOT NULL CHECK(length(status_upstream)<=1024), status_ahead INTEGER NOT NULL CHECK(status_ahead>=0 AND status_ahead<=1000000000), status_behind INTEGER NOT NULL CHECK(status_behind>=0 AND status_behind<=1000000000), status_tracked_dirty INTEGER NOT NULL CHECK(status_tracked_dirty>=0 AND status_tracked_dirty<=1000000000), status_untracked INTEGER NOT NULL CHECK(status_untracked>=0 AND status_untracked<=1000000000), status_ignored INTEGER NOT NULL CHECK(status_ignored>=0 AND status_ignored<=1000000000), status_confidence TEXT NOT NULL CHECK(status_confidence IN ('observed','incomplete','unknown')),
 merge_base_known INTEGER NOT NULL CHECK(merge_base_known IN (0,1)), merge_base_equals_head INTEGER NOT NULL CHECK(merge_base_equals_head IN (0,1)), default_counts_known INTEGER NOT NULL CHECK(default_counts_known IN (0,1)), default_ahead INTEGER NOT NULL CHECK(default_ahead>=0 AND default_ahead<=1000000000), default_behind INTEGER NOT NULL CHECK(default_behind>=0 AND default_behind<=1000000000), owner_registered INTEGER NOT NULL CHECK(owner_registered IN (0,1)), owner_state TEXT NOT NULL CHECK(owner_state IN ('unknown','active','waiting','ready','stale')),
 wt_path TEXT NOT NULL CHECK(length(wt_path)<=4096), wt_head TEXT NOT NULL CHECK(length(wt_head)<=1024), wt_branch TEXT NOT NULL CHECK(length(wt_branch)<=1024), wt_detached INTEGER NOT NULL CHECK(wt_detached IN (0,1)), wt_bare INTEGER NOT NULL CHECK(wt_bare IN (0,1)), wt_locked INTEGER NOT NULL CHECK(wt_locked IN (0,1)), wt_prunable INTEGER NOT NULL CHECK(wt_prunable IN (0,1)), wt_prune_reason TEXT NOT NULL CHECK(length(wt_prune_reason)<=4096), classification_json BLOB NOT NULL CHECK(json_valid(classification_json) AND json_type(classification_json)='array'), classification_confidence TEXT NOT NULL CHECK(classification_confidence IN ('observed','incomplete','unknown')),
 owner_session_id TEXT REFERENCES agent_sessions(id), owner_task_id TEXT REFERENCES tasks(id), owner_run_id TEXT REFERENCES task_runs(id), UNIQUE(observation_id,fingerprint)
);
CREATE INDEX idx_git_observations_project_time ON git_observations(project_id,observed_at DESC,id DESC); CREATE INDEX idx_git_assets_fingerprint ON git_observation_assets(fingerprint,first_seen_at);
CREATE TRIGGER git_observations_actor_lineage BEFORE INSERT ON git_observations BEGIN SELECT CASE WHEN NOT EXISTS(SELECT 1 FROM agent_sessions s JOIN tasks t ON t.id=NEW.task_id JOIN task_runs r ON r.id=NEW.run_id WHERE s.id=NEW.actor_session_id AND s.project_id=NEW.project_id AND t.project_id=NEW.project_id AND r.task_id=NEW.task_id AND r.session_id=NEW.actor_session_id) THEN RAISE(ABORT,'git observation actor lineage mismatch') END; END;
CREATE TRIGGER git_assets_owner_lineage BEFORE INSERT ON git_observation_assets BEGIN SELECT CASE WHEN NEW.owner_registered=0 AND (NEW.owner_session_id IS NOT NULL OR NEW.owner_task_id IS NOT NULL OR NEW.owner_run_id IS NOT NULL OR NEW.owner_state<>'unknown') THEN RAISE(ABORT,'unregistered git asset owner') END; SELECT CASE WHEN (NEW.owner_session_id IS NOT NULL OR NEW.owner_task_id IS NOT NULL OR NEW.owner_run_id IS NOT NULL) AND NEW.owner_registered<>1 THEN RAISE(ABORT,'unregistered git asset owner') END; SELECT CASE WHEN NEW.owner_session_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM agent_sessions s JOIN git_observations o ON o.id=NEW.observation_id WHERE s.id=NEW.owner_session_id AND s.project_id=o.project_id) THEN RAISE(ABORT,'git asset owner session mismatch') END; SELECT CASE WHEN NEW.owner_task_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM tasks t JOIN git_observations o ON o.id=NEW.observation_id WHERE t.id=NEW.owner_task_id AND t.project_id=o.project_id) THEN RAISE(ABORT,'git asset owner task mismatch') END; SELECT CASE WHEN NEW.owner_run_id IS NOT NULL AND NOT EXISTS(SELECT 1 FROM task_runs r JOIN tasks t ON t.id=r.task_id JOIN agent_sessions s ON s.id=r.session_id JOIN git_observations o ON o.id=NEW.observation_id WHERE r.id=NEW.owner_run_id AND t.project_id=o.project_id AND s.project_id=o.project_id AND (NEW.owner_task_id IS NULL OR r.task_id=NEW.owner_task_id) AND (NEW.owner_session_id IS NULL OR r.session_id=NEW.owner_session_id)) THEN RAISE(ABORT,'git asset owner run mismatch') END; END;
CREATE TRIGGER git_assets_registered_owner_required BEFORE INSERT ON git_observation_assets WHEN NEW.owner_registered=1 AND (NEW.owner_session_id IS NULL OR NEW.owner_task_id IS NULL OR NEW.owner_run_id IS NULL) BEGIN SELECT RAISE(ABORT,'registered git asset owner requires complete lineage'); END;
CREATE TRIGGER git_observations_timestamp_valid BEFORE INSERT ON git_observations BEGIN SELECT CASE WHEN COALESCE(strftime('%Y-%m-%dT%H:%M:%S',substr(NEW.observed_at,1,19))=substr(NEW.observed_at,1,19),0)=0 THEN RAISE(ABORT,'invalid git observation timestamp') END; END;
CREATE TRIGGER git_assets_timestamps_valid BEFORE INSERT ON git_observation_assets BEGIN SELECT CASE WHEN COALESCE(strftime('%Y-%m-%dT%H:%M:%S',substr(NEW.first_seen_at,1,19))=substr(NEW.first_seen_at,1,19),0)=0 OR COALESCE(strftime('%Y-%m-%dT%H:%M:%S',substr(NEW.last_seen_at,1,19))=substr(NEW.last_seen_at,1,19),0)=0 THEN RAISE(ABORT,'invalid git asset timestamp') END; END;
CREATE TRIGGER git_observations_no_update BEFORE UPDATE ON git_observations BEGIN SELECT RAISE(ABORT,'git observations are immutable'); END; CREATE TRIGGER git_observations_no_delete BEFORE DELETE ON git_observations BEGIN SELECT RAISE(ABORT,'git observations are retained'); END; CREATE TRIGGER git_assets_no_update BEFORE UPDATE ON git_observation_assets BEGIN SELECT RAISE(ABORT,'git observation assets are immutable'); END; CREATE TRIGGER git_assets_no_delete BEFORE DELETE ON git_observation_assets BEGIN SELECT RAISE(ABORT,'git observation assets are retained'); END;
